<?php

use Illuminate\Database\Seeder;

class TasksSeeder extends Seeder {

    public function run()
    {
        // Uncomment the below to wipe the table clean before populating

        $tasks = array(
            ['id' => 1, 'name' => 'Task 1', 'slug' => 'task-1', 'completed' => false, 'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum quam augue, tristique vel consequat id, dignissim at mi. Cras aliquam nibh quis mollis efficitur. Nam lobortis mattis arcu id aliquam. Nulla ac ligula ex. Cras pulvinar metus ac urna auctor, eget rutrum erat lacinia. Donec mollis porttitor vestibulum. Etiam suscipit feugiat arcu vitae consequat. Nullam egestas molestie nulla a fringilla. Integer ut est ut ante hendrerit rutrum. Aenean pellentesque consectetur mi nec molestie. Fusce ac nisl maximus, bibendum sem sed, faucibus diam. In vitae feugiat lacus. Fusce a elit laoreet, ultrices enim nec, gravida ante. Mauris ornare sem vitae condimentum pulvinar. Donec varius tristique risus, sit amet dignissim ante ultrices in. Sed enim purus, porta at ultrices sed, porta eget sapien.', 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['id' => 2, 'name' => 'Task 2', 'slug' => 'task-2', 'completed' => false, 'description' => 'Sed vehicula sit amet ex vitae maximus. Donec porttitor nunc quis magna bibendum, eget rhoncus tellus fringilla. Maecenas vel mi nec dui tempor posuere a non dolor. Morbi in faucibus ipsum, nec sollicitudin odio. Morbi ornare in ligula nec suscipit. Vivamus in auctor nisi. Sed purus nunc, porttitor id vulputate eget, pellentesque nec magna. Cras facilisis ex eget massa lacinia blandit. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean vitae luctus erat. Sed risus metus, eleifend ac tellus at, tincidunt porta ex. Nulla volutpat viverra augue vel blandit.', 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['id' => 3, 'name' => 'Task 3', 'slug' => 'task-3', 'completed' => false, 'description' => 'Cras finibus consequat elit ut faucibus. Integer vel eleifend risus. Phasellus viverra nec ipsum vel suscipit. Nam aliquam mollis massa ac dapibus. Vivamus luctus ornare erat. Suspendisse potenti. Quisque maximus felis arcu, non euismod enim fringilla quis. Duis euismod suscipit neque in maximus. Sed vehicula ullamcorper dictum. Nunc vehicula et ante quis facilisis.', 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['id' => 4, 'name' => 'Task 4', 'slug' => 'task-4', 'completed' => true, 'description' => 'In eleifend, ipsum nec volutpat sagittis, est leo tincidunt tellus, non viverra nunc erat et orci. Sed pellentesque leo scelerisque malesuada feugiat. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus ultricies, libero vel laoreet sollicitudin, leo libero mattis neque, a lacinia felis dui et sapien. Proin varius, lectus eget tempus pretium, neque augue imperdiet massa, vel dapibus urna nunc nec ligula. Donec pretium libero a sapien ultricies, in placerat tortor fermentum. Vestibulum sed tristique arcu. Vivamus condimentum, ex sed lobortis condimentum, orci nisl viverra augue, commodo pellentesque justo mi ac lacus. Nullam sagittis facilisis libero. Vestibulum sed sapien in lacus tempus ultrices.', 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['id' => 5, 'name' => 'Task 5', 'slug' => 'task-5', 'completed' => true, 'description' => 'Aenean et pulvinar orci. Morbi a elit vitae odio accumsan commodo. Sed quis convallis ipsum. Etiam gravida ante nisi, congue fermentum risus euismod vitae. Phasellus et convallis erat. In eu diam ligula. Sed sed urna vel ligula egestas gravida vel at felis. Donec nec egestas ligula, at pretium lacus. Praesent ullamcorper mi quam, ut tempus diam vestibulum et. Aliquam condimentum tincidunt velit, sed volutpat est rhoncus id. Phasellus tincidunt id dui a tristique. Pellentesque ut nisi eu urna lacinia luctus. Fusce lobortis, lectus in venenatis sollicitudin, eros justo laoreet libero, venenatis lobortis elit sapien in lorem. Quisque scelerisque lorem et lorem consequat, sed dignissim urna posuere.', 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['id' => 6, 'name' => 'Task 6', 'slug' => 'task-6', 'completed' => true, 'description' => 'Maecenas semper feugiat nisl, quis efficitur diam rhoncus eget. Cras ac sollicitudin arcu, eget elementum velit. Curabitur rutrum lacus lorem, sit amet molestie nibh iaculis vitae. Morbi tortor nisl, sagittis sit amet dictum vitae, blandit ut risus. Pellentesque nisi metus, dictum quis pulvinar et, volutpat ut elit. Aenean rutrum magna at est eleifend, vitae commodo nibh convallis. Vestibulum varius tempus mi sit amet volutpat. Morbi nisi neque, posuere at velit a, facilisis accumsan tortor. Pellentesque ultricies porttitor accumsan. Sed vehicula sit amet nibh ut faucibus. Vestibulum dignissim ac nunc ut hendrerit.', 'created_at' => new DateTime, 'updated_at' => new DateTime],
            ['id' => 7, 'name' => 'Task 7', 'slug' => 'task-7', 'completed' => false, 'description' => 'Vestibulum ac rutrum ante, in congue ex. Suspendisse quis ligula at nisl mollis egestas. Donec id tortor turpis. Cras tempor at massa sed fermentum. Praesent leo odio, congue interdum sem ut, maximus faucibus libero. Sed a efficitur felis. In hac habitasse platea dictumst.', 'created_at' => new DateTime, 'updated_at' => new DateTime],
        );

        //// Uncomment the below to run the seeder
        DB::table('tasks')->insert($tasks);
    }

}
